/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudioCourseIdRouteImport } from './routes/_authenticated/studio.$courseId'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioCourseIdRoute =
  AuthenticatedStudioCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/studio/$courseId': typeof AuthenticatedStudioCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/studio/$courseId': typeof AuthenticatedStudioCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/studio/$courseId': typeof AuthenticatedStudioCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/learn'
    | '/studio'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/studio/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/learn'
    | '/studio'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/studio/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/studio'
    | '/courses/$slug'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/studio/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/$courseId': {
      id: '/_authenticated/studio/$courseId'
      path: '/$courseId'
      fullPath: '/studio/$courseId'
      preLoaderRoute: typeof AuthenticatedStudioCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
  }
}

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioCourseIdRoute: typeof AuthenticatedStudioCourseIdRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioCourseIdRoute: AuthenticatedStudioCourseIdRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CoursesSlugRoute: CoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
